### ISSUE TITLE
Alerts email format - support for HTML

### ISSUE THREAD

**Issue by lioryantov** [johnsusek/praeco#127]
Hi, I noticed that if I edit the rule yaml file and add manually HTML section it is overwritten and them email is coming with an empty body. Will appreciate your efforts to look on the issue.
For example (simple rule with HTML Body without any parameters):

```
__praeco_full_path: Test-Rule2
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"beat.hostname","selectedOperator":"contains","selectedOperand":"beat.hostname","value":"testerver1"}}]}}
alert:
  - email
alert_subject: Elastalert - test alert for host testserver1
alert_subject_args: []
alert_text_args: []

alert_text_type: alert_text_only
email_format: html
alert_text: |
<h3>Alert!</h3>
  <p>Timestamp: </p>
  <p>Server: testserver1 </p>
    <p>This alert will not repeat for 15 min even if the situation is still happening.</p>
  <pre>

cc:
  - alerts-dl@mail.com
email:
  - alerts-dl@mail.com
filter:
  - query:
      query_string:
        query: 'beat.hostname:testserver1'
from_addr: elastalert@mail.com
import: BaseRule.config
index: filebeat-*
is_enabled: false
name: Test-Rule2
num_events: 10
realert:
  minutes: 10
reply_to: alerts-dl@mail.com
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: iso
type: frequency
use_strftime_index: false
```
