### ISSUE TITLE
Alert is not triggering for memory metric alert even though it reaches threshold 

### ISSUE THREAD

**Issue by suresh447** [johnsusek/praeco#193]
Hi,

I created a memory metric alert using praeco server and it is not triggering the alert if it reaches threshold which i set and i also found bug i am not able to give decimal values like 0.01 it is only taking 0.1 and above.

Condition what i gave is 

WHEN averageOF system.memory.used.pctGROUPED OVER metricset.nameWITH FILTER host.hostname:mgt-prd-unix-1 AND metricset.name:memoryIS ABOVE 0.5

![image](https://user-images.githubusercontent.com/33586664/75950904-9426ca00-5ed0-11ea-8b3d-e766c18b3ccf.png)

After giving this condition and i ran dry run it is giving

Test run finished
This rule would result in 0 alert triggers over the last 1 minute .
(This does not take into account your re-alert settings.)

Please help me on this

**Comment by daichi703n** [comment]
Hi, @suresh447 
At a moment, you can't use `average` rule.

Generated query URL is invalid. (tested on `.monitoring-es-*` index)

```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/.monitoring-es-*/properties/_search?pretty&ignore_unavailable=true&size=0' -d '{
```

`doc_type (properties)` is removed on ES7.x. Therefore, generated url is invalid and no result received.

This have to be below:

```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/.monitoring-es-*/_search?pretty&ignore_unavailable=true&size=0' -d '{
```

---

Hi, @johnsusek With ES7, doc_type have to be removed.
Would you please consider to remove this option?

<img width="682" alt="スクリーンショット 2020-03-06 23 31 48" src="https://user-images.githubusercontent.com/22485636/76092442-be78a480-6002-11ea-97b1-11c20725e5c1.png">

I have not traced your code yet...

**Comment by daichi703n** [comment]
@suresh447 Please show me you YAML.

This setting

<img width="1112" alt="スクリーンショット 2020-03-07 0 01 41" src="https://user-images.githubusercontent.com/22485636/76095013-e9fd8e00-6006-11ea-90e0-699435c20998.png">

with this yaml works for me.

```
__praeco_full_path: test.monitoring.average
__praeco_query_builder: '{"query":{"logicalOperator":"all","children":[]}}'
aggregation:
  schedule: '* * * * *'
alert:
  - slack
alert_subject: test praeco
alert_subject_args: []
alert_text_type: aggregation_summary_only
filter:
  - query:
      query_string:
        query: 'timestamp:*'
import: BaseRule.config
index: .monitoring-es-*
is_enabled: true
max_threshold: 0.1
metric_agg_key: node_stats.os.cpu.load_average.1m
metric_agg_type: avg
name: test.monitoring.average
query_key: source_node.host
realert:
  minutes: 0
slack_channel_override: '#alert'
slack_msg_color: warning
slack_title_link: 'http://praeco:8080/rules/test.monitoring.average'
slack_username_override: Praeco
summary_table_fields:
  - source_node.host
  - node_stats.os.cpu.load_average.1m
timestamp_field: timestamp
timestamp_type: iso
type: metric_aggregation
use_strftime_index: false
```

If your yaml contains `doc_type`, it cannot work because of the reason above. You have to empty on `All documents` and select `Field`.


<img width="650" alt="スクリーンショット 2020-03-07 0 05 43" src="https://user-images.githubusercontent.com/22485636/76095317-6d1ee400-6007-11ea-99f3-929346dbb881.png">

(Summary table cannot calcurate avg value...)

By using `Body text & trigger details & top counts`, value can be received.

<img width="633" alt="スクリーンショット 2020-03-07 0 13 43" src="https://user-images.githubusercontent.com/22485636/76095954-8b391400-6008-11ea-8b10-9d7fb378e5c0.png">

---

And I was able to set `0.01`. What is your problem? error?

<img width="1098" alt="スクリーンショット 2020-03-07 0 09 58" src="https://user-images.githubusercontent.com/22485636/76095771-30072180-6008-11ea-8125-6fd312b2194f.png">

```
__praeco_full_path: test.monitoring.average
...
is_enabled: true
max_threshold: 0.01
metric_agg_key: node_stats.os.cpu.load_average.1m
...
```
