### ISSUE TITLE
Request for support to "hive" integration like telegram, slack (New feature)

### ISSUE THREAD

**Issue by iamk-karthik** [johnsusek/praeco#208]
@johnsusek 
 Request for support to "hive" integration like telegram, slack (New feature)

**Comment by mdennison-ntc** [comment]
I would also be interested in this

**Comment by nsano-rururu** [comment]
@iamk-karthik 

I don't know about "hive" at all
Please let me know if you know the URL of the site that will be helpful in checking the operation of "hive". 
If possible, I would like to build an environment with docker-compose.yml.

**Comment by cvdjv** [comment]
https://github.com/TheHive-Project/TheHive
https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive

**Comment by nsano-rururu** [comment]
@cvdjv 

Thank you

**Comment by pingkrimson** [comment]
I would also be interested in this feature

**Comment by nsano-rururu** [comment]
There are currently no plans to add hive alerts. The reason is that the development of ElastAlert seems to be over. 
It's no longer maintained as I've seen it.

**Comment by nsano-rururu** [comment]
If you really want to support it, please write a concrete UI image.

https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive
- Hive_connection and hive_alert_config are required.
- The tag of hive_alert_config is a UI that allows you to add / change / delete multiple keywords.
- Hive_proxies is optional.
- I don't know what kind of setting the option hive_observable_data_mapping should be and what kind of UI should be used.

**Comment by nsano-rururu** [comment]
I see, if you can't answer the question, you don't need to respond. Really.

**Comment by iamk-karthik** [comment]
@nsano-rururu Thank you for bearing with my late reply.  I am not good in design.  But let me try and will give you the UI image.

**Comment by nsano-rururu** [comment]
@iamk-karthik

Let's develop in another branch and proceed while cooperating by checking the screen image and output contents. I'm not good at designing either.

**Comment by nsano-rururu** [comment]
@iamk-karthik

hive_observable_data_mapping is domain, domain, ip in the document, is this a fixed item? .. Please let me know if you know anything.
Perhaps it's a variable key, and you can specify multiple values in an array? .. I'm asking because I don't know about the hive at all.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive

```
hive_observable_data_mapping:
    - domain: "{match[field1]}_{rule[name]}"
    - domain: "{match[field]}"
    - ip: "{match[ip_field]}"
```

**Comment by nsano-rururu** [comment]
@iamk-karthik

Please answer even if you do not understand. I don't know. In that case, add a UI that allows you to set the required hive_connection and hive_alert_config on the screen.

**Comment by iamk-karthik** [comment]
I thing As like in telegram and email we need to have provision to add the following part(Which is common to all elast alert rules) of the hive configuration in **elastalert/rules/BaseRule.config** 

 **hive_connection:
   hive_host: http://localhost
   hive_port: <hive_port>
   hive_apikey: <hive_apikey>
   hive_proxies:
     http: ''
     https: ''**

The following may be given as configuration that varies with each rule. ( hive_alert_config )
![praeco_hive](https://user-images.githubusercontent.com/2486683/109481904-5fc5f980-7aa3-11eb-9450-7d54811cb7d2.png)

The existing configuration is looks as follows
![ref](https://user-images.githubusercontent.com/2486683/109482069-8c7a1100-7aa3-11eb-9f69-df7ded801626.png)

Thanks for understanding me neither an expert in hive sorry for that.

**Comment by iamk-karthik** [comment]
@nsano-rururu 

> @iamk-karthik
> 
> hive_observable_data_mapping is domain, domain, ip in the document, is this a fixed item? .. Please let me know if you know anything.
> Perhaps it's a variable key, and you can specify multiple values in an array? .. I'm asking because I don't know about the hive at all.
> https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive
> 
> ```
> hive_observable_data_mapping:
>     - domain: "{match[field1]}_{rule[name]}"
>     - domain: "{match[field]}"
>     - ip: "{match[ip_field]}"
> ```

domain, domain, ip are not fixed items

**Comment by nsano-rururu** [comment]
@iamk-karthik

hive_connection is BaseRule.config. hive_alert_config is set on the screen, isn't it? understood.
severity and tlp are numbers. Make the UI so that multiple tags can be registered. If follow is true and false, isn't it better to use radio buttons? Other than that, I will implement it as a character. Please point out if you make a mistake.
Details of the settings will be confirmed on thehive's official website at the time of implementation.

Example of setting thehive

```yaml
alert:
- hivealerter
 
hive_connection:
  hive_host: http://localhost
  hive_port: <hive_port>
  hive_apikey: <hive_apikey>
  hive_proxies:
   http: ''
   https: ''

hive_alert_config:
  title: 'Title'  ## This will default to {rule[index]_rule[name]} if not provided
  type: 'external'
  source: 'elastalert'
  description: '{match[field1]} {rule[name]} Sample description'
  severity: 2
  tags: ['tag1', 'tag2 {rule[name]}']
  tlp: 3
  status: 'New'
  follow: True
```
