### ISSUE TITLE
elastalert-server: ProcessController:  ElastAlert exited with code

### ISSUE THREAD

**Issue by vikas-prabhakar** [johnsusek/praeco#257]
Hi Praeco,

I am facing issues with elastalert-server. After a few minutes, it stopped working. Seems like some thread issues. I am facing it since I have updated the version. Even I pulled the latest branch but still showing updates available.

Current version: 1.3.0

Sharing some logs
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
ESC[36melastalert_1  |ESC[0m
ESC[36melastalert_1  |ESC[0m     Thread 0x00007fbd556bcb20 (most recent call first):
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/concurrent/futures/thread.py", line 78 in _worker
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.
ESC[36melastalert_1  |ESC[0m 11:51:13.398Z ERROR elastalert-server:
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.
ESC[36melastalert_1  |ESC[0m 11:51:13.398Z ERROR elastalert-server:
ESC[36melastalert_1  |ESC[0m     ProcessController:  8/threading.py", line 870 in run
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
ESC[36melastalert_1  |ESC[0m
ESC[36melastalert_1  |ESC[0m     Thread 0x00007fbd557bfb20 (most recent call first):
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 306 in wait
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 558 in wait
ESC[36melastalert_1  |ESC[0m       File "/home/node/.local/lib/python3.8/site-packages/apscheduler/schedu
ESC[36melastalert_1  |ESC[0m 11:51:13.398Z ERROR elastalert-server:
ESC[36melastalert_1  |ESC[0m     ProcessController:  lers/blocking.py", line 28 in _main_loop
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 870 in run
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
ESC[36melastalert_1  |ESC[0m
ESC[36melastalert_1  |ESC[0m     Thread 0x00007fbd578a4d48 (most recent call first):
ESC[36melastalert_1  |ESC[0m       File "/opt/elastalert/elastalert/elastalert.py", line 1321 in sleep_for
ESC[36melastalert_1  |ESC[0m       File "/opt/elastalert/elastalert/elastalert.py", line
ESC[36melastalert_1  |ESC[0m 11:51:13.399Z ERROR elastalert-server:
ESC[36melastalert_1  |ESC[0m     ProcessController:  1182 in start
ESC[36melastalert_1  |ESC[0m       File "/opt/elastalert/elastalert/elastalert.py", line 2051 in main
ESC[36melastalert_1  |ESC[0m       File "/opt/elastalert/elastalert/elastalert.py", line 2055 in <module>
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/runpy.py", line 86 in _run_code
ESC[36melastalert_1  |ESC[0m       File "/usr/lib/python3.8/runpy.py", line 193 in _run_module_as_main
ESC[36melastalert_1  |ESC[0m
ESC[36melastalert_1  |ESC[0m 11:51:13.541Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code

**Comment by nsano-rururu** [comment]
There is little information.
Please set docker-compose.yml.
Because it's not Esper

**Comment by nsano-rururu** [comment]
This is not happening in my environment

**Comment by nsano-rururu** [comment]
Investigation is impossible unless you tell me in detail how to reproduce

**Comment by nsano-rururu** [comment]
What did you do

**Comment by nsano-rururu** [comment]
Since we can not support usage other than docker

**Comment by nsano-rururu** [comment]
All operations, configuration file please

**Comment by nsano-rururu** [comment]
We will not investigate until you provide information

**Comment by nsano-rururu** [comment]
The reason is that we do not know that the same phenomenon will occur.

**Comment by nsano-rururu** [comment]
Please inform me soon

**Comment by vikas-prabhakar** [comment]
docker-compose file
`version: '3'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
        #extra_hosts:
        #- 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf`


elastalert.yaml
`es_host: "elasticsearch_host(behind the NLB)"

es_port: 9200
es_conn_timeout: 60

rules_folder: rules

run_every:
  seconds: 60

buffer_time:
  minutes: 1





es_username: ********
es_password: ********

writeback_index: praeco_elastalert_status

alert_time_limit:
  days: 2

skip_invalid: True`

api.config.json
`{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch_host(behind the NLB)",
  "es_port": 9200,
  "es_username": "*******",
  "es_password": "*******",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}`

**Comment by vikas-prabhakar** [comment]
I have deployed it via docker.

**Comment by nsano-rururu** [comment]
>`es_host: "elasticsearch_host(behind the NLB)"

What kind of structure is elasticsearch?
What version?
Are you running another host with docker?

**Comment by vikas-prabhakar** [comment]
elasticsearch version: 7.3.2
elasticsearch is behind the AWS NLB.
praeco/elast-server running on different node via docker.

**Comment by nsano-rururu** [comment]
Amazon Elasticsearch Service？

**Comment by vikas-prabhakar** [comment]
Self managed Elasticsearch.

**Comment by nsano-rururu** [comment]
We have not confirmed the operation with the desired configuration, so the cause is still unknown.

By the way, is it a problem caused by using ElastAlert Server and Praeco all the time in this configuration and upgrading the version, or is it a problem caused by running ElastAlert Server and Praeco in this configuration for the first time this time?

**Comment by vikas-prabhakar** [comment]
Thanks for the support.

I am facing this issue since I upgraded the version. I am also trying to figure out & will let you the know the root cause along with fix.

**Comment by nsano-rururu** [comment]
By the way, which version of docker image I used before is serversentral or johnsusek?

servercentral/elastalert
https://hub.docker.com/r/servercentral/elastalert
servercentral/praeco
https://hub.docker.com/r/servercentral/praeco

johnsusek/elastalert-server
https://hub.docker.com/r/johnsusek/elastalert-server
johnsusek/praeco
https://hub.docker.com/r/johnsusek/praeco

**Comment by nsano-rururu** [comment]
servercentral / elastalert is Python 3.6.8 & ElastAlert 0.2.1.
johnsusek / elastalert-server is Python 3.8 & ElastAlert 0.2.4.

**Comment by nsano-rururu** [comment]
If you used servercentral, I'm thinking of releasing a reverted version of Python.

**Comment by vikas-prabhakar** [comment]
Earlier I used johnsusek  docker image. Post upgrade, I observed some issues then I did cleanup & reconfigure the the preaco with latest docker-compose file

**Comment by nsano-rururu** [comment]
The fact that I used the johnsusek docker image did not occur because I upgraded the Python version. Is it a change after that?

**Comment by nsano-rururu** [comment]
You need to find out if any of these changes are the cause

Maybe stop_on_elastalert_exit is the problem?
I've incorporated support for bitsensor
It's still a guess, but ...
https://github.com/johnsusek/elastalert-server/commits/master

| Docker image name    |   Remarks    |
|:-------------------|:-----------|
|praecoapp/elastalert-server:20200810|Commits on Aug 9, 2020<br>・Merge pull request 3 from nsano-rururu/stop_on_elastalert_exit<br>・Merge pull request 2 from nsano-rururu/zabbix-sns<br>Commits on Aug 10, 2020<br>・Update Makefile|
|praecoapp/elastalert-server:20200823|Commits on Aug 23, 2020<br>・Twilio / PagerTree support & Bugfix|
|praecoapp/elastalert-server:20200823-2|Commits on Aug 23, 2020<br>・Fix failed to create a folder|
|praecoapp/elastalert-server:20200825|Commits on Aug 25, 2020<br>・Fix Promise Error Handling|
|praecoapp/elastalert-server:20200831|Commits on Aug 29, 2020<br>・Update README.md<br>Commits on Aug 31, 2020<br>・Bugfix, Library Update|

The following commits have not been released yet
I plan to make a docker image in the next release

Commits on Sep 7, 2020
　Library Update
Commits on Oct 7, 2020
　Change New Elasticsearch Node.js Client

**Comment by nsano-rururu** [comment]
I'm worried that this is an error that has never occurred when running elasticsearch, kibana, elastalertserver, and praeco on the same docker host. If it happens in the first place, you should notice it immediately when you change it and check the operation.

**Comment by nsano-rururu** [comment]
By the way, the environment for my operation check is as follows.

Amazon Workspaces
・ Amazon Linux2
・ Elasticserach 7.9.2
・ Kibana 7.9.2
・ praecoapp/elastalert-server:latest
・ praecoapp praeco:latest

```
/home/sano/dkwork2/es
|--Dockerfiles
|  |--Dockerfile.elastalert
|--docker-compose.yml
|--es
|  |--config
|  |  |--elasticsearch.yml
|  |--data
|--kibana
|  |--config
|  |  |--kibana.yml
|--praeco
|  |--bin
|  |  |--elastalert-start.sh
|  |  |--elastic_search_status.sh
|  |--config
|  |  |--api.config.json
|  |  |--elastalert.yaml
|  |--nginx_config
|  |  |--default.conf
|  |  |--nginx.conf
|  |--public
|  |  |--favicon.ico
|  |  |--index.html
|  |  |--js
|  |  |  |--cron-ui.min.js
|  |  |--praeco.config.json
|  |--rule_templates
|  |--rules
|  |  |--BaseRule.config
|--fluentd
|  |--dockerfiles
|  |  |--Dockerfile
|  |--etc
|  |  |--fluent.conf
|--mariadb
|  |--data
|  |--etc
|  |  |--mymariadb.cnf
|  |--log
|  |  |--error.log
|  |  |--general.log
|  |  |--slow.log
```

**Dockerfiles/Dockerfile.elastalert**

```
FROM praecoapp/elastalert-server:latest

USER root

RUN apk update && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

ADD praeco/bin/elastalert-start.sh /usr/local/bin/
ADD praeco/bin/elastic_search_status.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/elastalert-start.sh 
RUN chmod +x /usr/local/bin/elastic_search_status.sh

USER node

ENTRYPOINT ["/usr/local/bin/elastalert-start.sh"]
```

**docker-compose.yml**

```
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 180s

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
 
  elastalert:
    container_name: elastalert
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.elastalert
    image: elastalert-server:3.0.0
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./praeco/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./praeco/rules:/opt/elastalert/rules
      - ./praeco/rule_templates:/opt/elastalert/rule_templates
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  praeco:
    container_name: praeco
    image: praecoapp/praeco:latest
    ports:
      - 8080:8080
    depends_on:
      - elastalert
    restart: always
    volumes:
      - ./praeco/public/praeco.config.json:/var/www/html/praeco.config.json
      - ./praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  fluentd:
    container_name: fluentd
    build: ./fluentd/dockerfiles
    image: fluentd:1.9.3
    ports:
      - 24224:24224
      - 24224:24224/udp
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluentd/etc/fluent.conf:/fluentd/etc/fluent.conf
      - ./mariadb/log:/var/log/mysql
    user: root
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb:10.4.12
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    volumes:
      - ./mariadb/etc:/etc/mysql/conf.d
      - ./mariadb/log:/var/log/mysql
    restart: always
```


**es/config/elasticsearch.yml**

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

**kibana/config/kibana.yml**

```
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
```

**praeco/bin/elastalert-start.sh**

```
#!/bin/bash

set -e

echo "Giving Elasticsearch at $ELASTICSEARCH_URL time to start..."

elastic_search_status.sh

echo "Starting ElastAlert!"
npm start
```

**praeco/bin/elastic_search_status.sh**

```
#!/bin/bash

set -e

if [ $# -gt 0 ]; then
  ES_URL="$1"
elif [[ -n $ELASTICSEARCH_URL ]]; then
  ES_URL="$ELASTICSEARCH_URL"
elif [[ -n $ES_HOST ]] && [[ -n $ES_PORT ]]; then
  ES_URL="http://$ES_HOST:$ES_PORT"
else
  ES_URL="http://elasticsearch:9200"
fi

until [[ "$(curl -fsSL "$ES_URL/_cat/health?h=status" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" =~ ^(yellow|green)$ ]]; do
  # printf '+' >&2
  sleep 1
done

echo "Elasticsearch is up and healthy at "$ES_URL"" >&2
```

**praeco/config/api.config.json**

Default settings

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
```

**praeco/config/elastalert.yaml**

Default settings

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True

profile: default
```

**praeco/public/praeco.config.json**

Default settings

```
{
  "appUrl": "http://127.0.0.1:8080",
  "errorLoggerUrl": "",
  "hidePreconfiguredFields": []
}
```

**praeco/rules/BaseRule.config**

```
telegram_bot_token: 'xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

**fluentd/dockerfiles/Dockerfile**

```
FROM fluent/fluentd:v1.9.3-debian-1.0

# Use root account to use apt
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN buildDeps="sudo make gcc g++ libc-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo gem install fluent-plugin-elasticsearch -v 4.0.6 \
 && sudo gem install fluent-plugin-mysqlslowquery -v 0.0.9 \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER fluent
```

**fluentd/etc/fluent.conf**

```
<source>
  @type mysql_slow_query
  path /var/log/mysql/slow.log
  pos_file /tmp/mysql/slow.pos
  tag mysqld.slow_query
   <parse>
     @type none
   </parse>
</source>
<source>
  @type tail
  format none
  path /var/log/mysql/general.log
  pos_file /tmp/mysql/general.pos
  tag mysqld.general
</source>
<source>
  @type tail
  format none
  path /var/log/mysql/error.log
  pos_file /tmp/mysql/error.pos
  tag mysqld.error
</source>

<match **.**>
  @type copy
  <store>
    @type stdout
  </store>
  <store>
    @type elasticsearch
    include_tag_key true
    tag_key @log_name
    logstash_format true
    logstash_prefix mariadb-log
    host elasticsearch
    port 9200
    index_name mysql
    flush_interval 10s
  </store>
</match>
```

**mariadb/etc/mymariadb.cnf**

```
[mysqld]
general_log
general_log_file=/var/log/mysql/general.log
slow_query_log
slow_query_log_file=/var/log/mysql/slow.log
long_query_time=5 
log-queries-not-using-indexes
log-error=/var/log/mysql/error.log
```

**setting**

```
cd /home/sano/dkwork2/es
chmod 777 es/data
chmod 777 mariadb/data
chmod 777 mariadb/log
chmod -R 777 praeco/rules praeco/rule_templates
docker-compose up -d
```
