### ISSUE TITLE
Add optional HTTP post options

### ISSUE THREAD

**Issue by micwiec** [johnsusek/praeco#267]
@johnsusek 
Can you add in HTTP POST  UI option to define `http_post_static_payload`?

In ElastAlert YAML it might like this:
```yml
[...]
http_post_static_payload:
    error_id: XYZ_123
    error_description: "There is a problem with XYZ."
```

ElastAlert Doc: [https://elastalert.readthedocs.io/en/latest/ruletypes.html#http-post](https://elastalert.readthedocs.io/en/latest/ruletypes.html#http-post)
