### ISSUE TITLE
Incorrect matches

### ISSUE THREAD

**Issue by azhinu** [johnsusek/praeco#270]
Hi everyone. I have praeco deployed with docker-compose and it march events incorrectly.
I have this rule
``` yaml
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"status","selectedOperator":"contains","selectedOperand":"status","value":"failed"}}]}}
alert:
  - telegram
alert_subject: 'test'
alert_subject_args: []
alert_text: 'test body'
alert_text_args: []
alert_text_type: alert_text_only
doc_type: properties
filter:
  - query:
      query_string:
        query: 'status:failed'
import: BaseRule.config
index: some-index-*
is_enabled: true
name: Name
num_events: 1
realert:
  minutes: 20
telegram_room_id: 'id'
terms_size: 50
timeframe:
  minutes: 30
timestamp_field: '@timestamp'
timestamp_type: iso
type: frequency
use_strftime_index: false
```
And for some reason then I try to test rule with test button everything is correct but actually it doesnt match events. I doesn't getted any allerts for a days but there was 3 eventh per 30  minutes twice. And now I got an alert but there was only 1 event.

<img width="485" alt="Screen Shot 2020-10-29 at 12 37 17" src="https://user-images.githubusercontent.com/65022127/97553171-30648a80-19e6-11eb-9d54-978c0ad8bb51.png">
<img width="2564" alt="Screen Shot 2020-10-29 at 12 37 03" src="https://user-images.githubusercontent.com/65022127/97553179-322e4e00-19e6-11eb-82c2-41cc201a63fd.png">
