### ISSUE TITLE
Docker composer with ES included

### ISSUE THREAD

**Issue by priamai** [johnsusek/praeco#285]
Hi there,
what would be the best way to use ES in a docker composer file?

```
version: '3'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
      - 'elasticsearch:elasticsearch'
    depends_on:
      - elasticsearch

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
#    environment:
#      VUE_APP_BASE_URL: /my-path/
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elastalert

volumes:
  elasticsearch-data:
    driver: local
```
It gives me:

```
ERROR: for elastalert  Cannot create container for service elastalert: invalid IP address in add-host: "elasticsearch"
ERROR: Encountered errors while bringing up the project.

```

Is there a way to provide a hostname and not an IP address that I cannot recover from during the composer sequence?
