### ISSUE TITLE
Please can add Alerta to send notifications

### ISSUE THREAD

**Issue by CyberAbwehr** [johnsusek/praeco#330]
doc: https://elastalert.readthedocs.io/en/latest/ruletypes.html#alerta

Rulefile Example:

alert:
  - alerta
alerta_api_url: "http://192.168.0.10:8180/api/alert"
alerta_api_key: "jsadgkasjdgakjsdgaskjdgaskjdgasdkjg"
alerta_severity: "critical"
alerta_text: 'Docker Container CPU fully occupied'
alerta_event: 'Docker Container CPU fully occupied'
alerta_group: 'OS'

best regards

**Comment by nsano-rururu** [comment]
@CyberAbwehr

Is there any problem with the following specifications for the UI of the setting screen? Please point out any mistakes.

|config| default value |input|remark|
|------|---------------|------|------|
|alerta_api_url|None|el-input|Required|
|alerta_api_key|None|el-input|Optional|
|alerta_timeout|86400|el-input-number|Optional|
|alerta_use_match_timestamp|false|el-switch |Optional|
|alerta_use_qk_as_resource|false|el-switch |Optional|
|alerta_api_skip_ssl|false|el-switch |Optional|
|alert_missing_value|'<MISSING VALUE>'|el-input|Optional|
|alerta_severity|'warning'|el-select<br>unknown, security, debug, informational, ok, normal, cleared, indeterminate, warning, minor, major, critical|Optional|
|alerta_resource|'elastalert'|el-input|Optional|
|alerta_environment|'Production'|el-input|Optional|
|alerta_origin|'elastalert'|el-input|Optional|
|alerta_service||list。UI to add / update / delete key|Optional|
|alerta_text|'elastalert'|el-input|Optional|
|alerta_type|'elastalert'|el-input|Optional|
|alerta_event|'elastalert'|el-input|Optional|
|alerta_correlate||list。UI to add / update / delete key|Optional|
|alerta_tags||[list。UI to add / update / delete key|Optional|
|alerta_group|''|el-input|Optional|
|alerta_attributes_keys||list。UI to add / update / delete key|Optional|
|alerta_attributes_values||list。UI to add / update / delete value|Optional|
|alerta_value|''|el-input|Optional|

**Comment by nsano-rururu** [comment]
Will work on the following branches
https://github.com/johnsusek/praeco/tree/alerta_support

**Comment by nsano-rururu** [comment]
@CyberAbwehr

I would like to know if all items are supported or if only the following items in the first post are supported for the time being.

```yaml
alerta_api_url: "http://192.168.0.10:8180/api/alert"
alerta_api_key: "jsadgkasjdgakjsdgaskjdgaskjdgasdkjg"
alerta_severity: "critical"
alerta_text: 'Docker Container CPU fully occupied'
alerta_event: 'Docker Container CPU fully occupied'
alerta_group: 'OS'
```

**Comment by CyberAbwehr** [comment]
I have know following components installed to make test.

elastic: 7.10.2
praeco: 1.7.0
Alerta API: 8.4.1

Rule File:

![Bildschirmfoto 2021-03-15 um 14 32 00](https://user-images.githubusercontent.com/51229037/111161253-3a54e780-859b-11eb-893f-c8d2f6462ce9.png)

Normal I put following keys into the BaseConfig.json file
alerta_api_url: 
alerta_api_key: 

Output Alerta:

![Bildschirmfoto 2021-03-15 um 14 25 20](https://user-images.githubusercontent.com/51229037/111160590-881d2000-859a-11eb-8044-2f1d4f673f29.png)

**Comment by nsano-rururu** [comment]
@CyberAbwehr

Please answer the question.

**Comment by CyberAbwehr** [comment]
In the past some of the values have not worked, in the list that you post.
Maybe there are some changes now in the new Alerta version.

Following Values I have test and they are working:

alerta_api_url: 
alerta_api_key:
alerta_severity:
alerta_resource:
alerta_text:
alerta_event:
alerta_group:
alerta_tags:

**Comment by nsano-rururu** [comment]
@CyberAbwehr

thank you for your answer. We will start to make it possible to set the items you contacted.

alerta_api_url:
alerta_api_key:
alerta_severity:
alerta_resource:
alerta_text:
alerta_event:
alerta_group:
alerta_tags:

**Comment by nsano-rururu** [comment]
@CyberAbwehr

If there is no problem on the screen below, merge it with master and release it as 1.8.0.
https://github.com/johnsusek/praeco/tree/alerta_support

![1](https://user-images.githubusercontent.com/22293449/111184766-a31c7e00-85f4-11eb-81d7-71c1a0bf48aa.PNG)
![2](https://user-images.githubusercontent.com/22293449/111184782-a6b00500-85f4-11eb-89f2-0fb986b1a4c9.PNG)
![3-0](https://user-images.githubusercontent.com/22293449/111184798-aadc2280-85f4-11eb-9c70-007fa97fe911.PNG)
![3](https://user-images.githubusercontent.com/22293449/111184822-b0396d00-85f4-11eb-8aad-e6b43c145f8f.PNG)

**Comment by CyberAbwehr** [comment]
Looks perfect ;-)

**Comment by nsano-rururu** [comment]
Praeco has released a new docker image. 1.8.0
https://hub.docker.com/r/praecoapp/praeco

**Comment by CyberAbwehr** [comment]
THX for the new version.

I have made some tests today.

Some notes:

- alerta_severity
    all severities needs to be defined in the alertad.conf configuration file.
    Standard definitions is: 
    fatal, critical, major, minor, warning, indeterminate, cleared, normal, ok, informational, debug, trace, unknown

- alert_text_args: [] & alert_subject_args: []

    where can i define this values in the GUI ?
    I need that to define as example alerts like

    alert_subject: "The following file {} has been {} on the {}"
    alert_subject_args:
        - file.path
        - event.action
        - agent.hostname

    alert_text: "The following file {} has been {} on the {}"
    alert_text_args:
        - file.path
        - event.action
        - agent.hostname

    alerta_severity: "minor"
    alerta_resource: '{agent[hostname]}'
    alerta_text: 'The following file {file[path]} has been {event[action]} on the {agent[hostname]}'
    alerta_event: '{file[path]} {event[action]}'
    alerta_group: 'Security'

- alert_text_type:
    is it possible to have the option to disable this value in the GUI?
    because I want to send the full original alert information.

best regards

**Comment by CyberAbwehr** [comment]
Please can you add the value alerta_environment
THX

best regards

**Comment by nsano-rururu** [comment]
Say it from the beginning. what is it. Do not be silly. Later this and this too. Not possible this week. I am busy with my work

**Comment by CyberAbwehr** [comment]
THX for your feedback.

Sorry for all my comments, I only start testing to rebuild my rules with the new GUI.
I figured out that I use a lot of functions from elastalert in the past to build reasonable Alerts.

So take your time, am happy to see that this project is good maintened !!! :-) :-) :-) 

best regards

My notes:

- alerta_severity
    all severities needs to be defined in the alertad.conf configuration file.
    Standard definitions is: 
    fatal, critical, major, minor, warning, indeterminate, cleared, normal, ok, informational, debug, trace, unknown

- alert_text_args: [] & alert_subject_args: []

    where can i define this values in the GUI ?
    I need that to define as example a values like

    alert_subject: "The following file {} has been {} on the {}"
    alert_subject_args:
        - file.path
        - event.action
        - agent.hostname

    alert_text: "The following file {} has been {} on the {}"
    alert_text_args:
        - file.path
        - event.action
        - agent.hostname

    alerta_severity: "minor"
    alerta_resource: '{agent[hostname]}'
    alerta_text: 'The following file {file[path]} has been {event[action]} on the {agent[hostname]}'
    alerta_event: '{file[path]} {event[action]}'
    alerta_group: 'Security'

- alerta_environment
    please can you add this value 

- Some information to the alerta application
    When an alert with the same environment-resource-event combination is received with the same severity, the alert is de-duplicated.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml#L357

alerta_new_style_string_format and alerta_customer are not used. There are two alerta_services. It doesn't hurt. It seems that schema.yaml is used to check the value when notifying the alert of the rule.
```yaml
 ### Alerta
  alerta_api_url: {type: string}
  alerta_api_key: {type: string}
  alerta_severity: {enum: [unknown, security, debug, informational, ok, normal, cleared, indeterminate, warning, minor, major, critical]}
  alerta_resource: {type: string}   # Python format string
  alerta_environment: {type: string}  # Python format string
  alerta_origin: {type: string}   # Python format string
  alerta_group: {type: string}  # Python format string
  alerta_service: {type: array, items: {type: string}}  # Python format string
  alerta_service: {type: array, items: {type: string}}  # Python format string
  alerta_correlate: {type: array, items: {type: string}}  # Python format string
  alerta_tags: {type: array, items: {type: string}}   # Python format string
  alerta_event: {type: string} # Python format string
  alerta_customer: {type: string}
  alerta_text: {type: string} # Python format string
  alerta_type: {type: string}
  alerta_value: {type: string} # Python format string
  alerta_attributes_keys: {type: array, items: {type: string}}
  alerta_attributes_values: {type: array, items: {type: string}}  # Python format string
  alerta_new_style_string_format: {type: boolean}
```

---

Customer's additional pull request
[Alerta: Add Customer in Alert Payload](https://github.com/Yelp/elastalert/pull/2269)

Alerta documentation pull request
[Update documentation for percentage_format_string and alerta_timeout](https://github.com/Yelp/elastalert/pull/2537)

Source code of the alerta part of elastalert
https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1837

Alerta API Reference
https://docs.alerta.io/en/latest/api/reference.html
