### ISSUE TITLE
Error posting HTTP Post alert - elastalert-server

### ISSUE THREAD

**Issue by karthiknagraj** [johnsusek/praeco#386]
## 🐛 Summary
I am using praecoapp/elastalert-server:20210609 docker image. I have configured Alerta webhook  to receive an alert from elastalert server. Below is the rule file.
```

name: alertrule-1
type: any
index: fluentd*
timestamp_field: "@timestamp"
realert:
  minutes: 1
filter:
\- query:
    query_string:
      query: "Name: \"Example Alert Occurred\""
alert:
\- post:
    http_post_url: "http://localhost/api/webhooks/elastalert"
alert_text: "critical alert raised" 

```

Configuration used to connect to elasticsearch
```

rules_folder: /opt/elastalert/rules
run_every:
  seconds: 60
buffer_time:
  minutes: 5
es_host: localhost
es_port: 9200
es_username: example
es_password: example-password
writeback_index: elastalert_status
use_ssl: false
alert_time_limit:
  days: 2

```

I am seeing the below-shown error message while sending alerts to Alerta from elastalert-server
```

10:58:26.472Z ERROR elastalert-server:
    ProcessController:  ERROR:elastalert:Error while running alert http_post: Error posting HTTP Post alert: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost/api/webhooks/elastalert

```

## 👀 Steps

(Bug reproduction procedure)

1. Bring up elastalert server as a kubernetes deployment with the above-shown rule file configured to send alerts to Alerta
2. Generate a dummy log and send it to elasticsearch so that elastalert and trigger alert for this log

## 🆗 Expected
In kubernetes pod of elastalert-server, we should not see above shown error message.
