### ISSUE TITLE
[elastalert-server]     elasticsearch.exceptions.SerializationError: Unknown mimetype

### ISSUE THREAD

**Issue by tracylucky** [johnsusek/praeco#389]
## 🐛 Summary

# When I started elastalert-server followed the steps:
docker pull python:3.9-alpine3.14 && docker pull node:16.4.2-alpine3.14
docker build -t elastalert-server .

# Then run docker in the server
docker run -it -p 8080:3030  -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml   -v `pwd`/config/elastalert.yaml:/opt/elastalert/config-test.yaml -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json    -v `pwd`/rules:/opt/elastalert/rules:rw    -v `pwd`/rule_templates:/opt/elastalert/rule_templates:rw    -v `pwd`/cert:/opt/elastalert-server/config/    --name elastalert elastalert-server:latest
# Error message:
ProcessController:  ERROR:apscheduler.executors.default:Job "Internal: Handle Pending Alerts (trigger: interval[0:00:05], next run at: 2021-08-10 09:48:26 UTC)" raised an exception
    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.9/site-packages/elasticsearch/serializer.py", line 160, in loads
        deserializer = self.serializers[mimetype]
    KeyError: 'text/html'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
        retval = job.func(*job.args, **job.kwargs)
      File "/opt/elastalert/elastalert/elastalert.py", line 1288, in handle_pending_alerts
        self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1716, in send_pending_alerts
        pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1698, in find_recent_pending_alerts
        if self.writeback_es.is_atleastfive():
      File "/opt/elastalert/elastalert/__init__.py", line 63, in is_atleastfive
        return int(self.es_version.split(".")[0]) >= 5
      File "/opt/elastalert/elastalert/__init__.py", line 51, in es_version
        self._es_version = self.info()['version']['number']
      File "/home/node/.local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
        return func(*args, params=params, headers=headers, **kwargs)
      File "/home/node/.local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 286, in info
        return self.transport.perform_request(
      File "/home/node/.local/lib/python3.9/site-packages/elasticsearch/transport.py", line 402, in perform_request
        data = self.deserializer.loads(
      File "/home/node/.local/lib/python3.9/site-packages/elasticsearch/serializer.py", line 162, in loads
        raise SerializationError(
    elasticsearch.exceptions.SerializationError: Unknown mimetype, unable to deserialize: text/html`
## 👀 Operating environment

- Direct installation or docker
Docker
- elasticsearch version
 **7.5.2**
{
  "name" : "test-elasticsearch-ewe-hybrid-10.2.13.209",
  "cluster_name" : "test-elasticsearch-ewe",
  "cluster_uuid" : "esXuBKBdQ6qv-MZABArZTg",
  "version" : {
    "number" : "7.5.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "8bec50e1e0ad29dad5653712cf3bb580cd1afcdf",
    "build_date" : "2020-01-15T12:11:52.313576Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

- version of praeco
Not use praeco
- elastalert-server docker image tag name
2.1.2

## Dockerfile
 _I tried with RUN pip3 install "elasticsearch==7.5.1", there is also error, so I tried to update to 7.10.0 in Dockerfile
The following info is what I got from kibana_

FROM python:3.9-alpine3.14 as py-ea
ARG ELASTALERT_VERSION=2.1.2
ENV ELASTALERT_VERSION=${ELASTALERT_VERSION}
ARG ELASTALERT_URL=https://github.com/jertel/elastalert2/archive/refs/tags/$ELASTALERT_VERSION.zip
ENV ELASTALERT_URL=${ELASTALERT_URL}
ENV ELASTALERT_HOME /opt/elastalert

WORKDIR /opt

RUN apk add --update --no-cache wget && \
    wget -O elastalert.zip "${ELASTALERT_URL}" && \
    unzip elastalert.zip && \
    rm elastalert.zip && \
    mv e* "${ELASTALERT_HOME}"

WORKDIR "${ELASTALERT_HOME}"

FROM node:16.4.2-alpine3.14
LABEL maintainer="John Susek <john@johnsolo.net>"
ENV TZ Etc/UTC
ENV PATH /home/node/.local/bin:$PATH

RUN apk add --update --no-cache \
    ca-certificates \
    cargo \
    curl \
    gcc \
    libffi-dev \
    libmagic \
    make \
    musl-dev \
    openssl \
    openssl-dev \
    py3-pip \
    python3 \
    python3-dev \
    tzdata

#COPY --from=py-ea /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=py-ea /opt/elastalert /opt/elastalert
#COPY --from=py-ea /usr/local/bin/elastalert* /usr/bin/

WORKDIR /opt/elastalert-server
COPY . /opt/elastalert-server

RUN npm install --production --quiet
COPY config/elastalert.yaml /opt/elastalert/config.yaml
COPY config/config.json config/config.json
COPY rule_templates/ /opt/elastalert/rule_templates
COPY elastalert_modules/ /opt/elastalert/elastalert_modules

#Add default rules directory
#Set permission as unpriviledged user (1000:1000), compatible with Kubernetes
RUN mkdir -p /opt/elastalert/rules/ /opt/elastalert/server_data/tests/ \
    && chown -R node:node /opt

RUN pip3 install --no-cache-dir --upgrade pip==21.1.3

USER node

EXPOSE 3030

WORKDIR /opt/elastalert

RUN pip3 install --no-cache-dir cryptography --user
RUN pip3 install --no-cache-dir -r requirements.txt --user
RUN pip3 install "elasticsearch==7.10.1"
WORKDIR /opt/elastalert-server
ENTRYPOINT ["npm", "start"]

Thanks a lot

**Comment by nsano-rururu** [comment]
>I tried with RUN pip3 install "elasticsearch==7.5.1", there is also error, so I tried to update to 7.10.0 in Dockerfile
The following info is what I got from kibana

If you raise the elasticsearch library, it will not move normally according to the rules of elastalert2, so I dare to fix it to "7.0.0". If you dare to mention it, you can only say that you should solve it yourself. It is your own responsibility.

**Comment by nsano-rururu** [comment]
The files in the following locations are not maintained, so it is unknown whether they are up to date.
https://github.com/johnsusek/elastalert-server/tree/master/config

**Comment by nsano-rururu** [comment]
>pwd/cert:/opt/elastalert-server/config/ 

what is this?

**Comment by nsano-rururu** [comment]
I want to know if there is a way to isolate the problem.

**Comment by nsano-rururu** [comment]
- Does the problem occur with the docker image published on dockerhub?
 - Is the host name of elasticsearch set in elastalert.yaml and config.json a setting value that can be accessed from the docker container?

I think the second one is suspicious.

**Comment by nsano-rururu** [comment]
If no information is provided, it will be closed.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/594

**Comment by nsano-rururu** [comment]
I will open it if there is a reply.

**Comment by nsano-rururu** [comment]
```sh
/home/user/dkwork2/es
|--docker-compose.yml
|--es
|  |--config
|  |  |--elasticsearch.yml
|  |--data
|--kibana
|  |--config
|  |  |--kibana.yml
```

docker-compose.yaml

```yaml
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 180s

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```


es/config/elasticsearch.yml

```yaml
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

kibana/config/kibana.yml

```yaml
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
```

```sh
mkdir -p es/data
chmod 777 es/data
docker-compose up -d
```

```
/home/sano/dkwork3/aa/elastalert-server
|--config
|  |--config.json
|  |--elastalert.yaml
|--rule_templates
|--rules
```

```sh
cd
cd /home/sano/dkwork3/aa/elastalert-server
chmod 777 rules rule_templates
```

config/config.json

```json
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "elastalert_status"
}
```

config/elastalert.yaml

```yaml
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True
```

```sh
docker run -d -p 3030:3030 -p 3333:3333 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    --net="es_default" \
    --name elastalert praecoapp/elastalert-server:latest
```
