### ISSUE TITLE
An error occurs when the elastalert-server starts

### ISSUE THREAD

**Issue by marakhand** [johnsusek/praeco#403]
## 🐛 Summary

An error occurs when the elastalert-server starts:

06:33:35.992Z INFO elastalert-server: ProcessController: Creating index
06:33:36.042Z ERROR elastalert-server:
ProcessController: /usr/bin/python3: Error while finding module specification for 'elastalert.create_index' (ModuleNotFoundError: No module named 'elastalert')
06:33:36.042Z ERROR elastalert-server: ProcessController: Index create exited with code 1
...
06:33:36.054Z INFO elastalert-server: Server: Server started
06:33:36.089Z ERROR elastalert-server:
ProcessController: /usr/bin/python3: Error while finding module specification for 'elastalert.elastalert' (ModuleNotFoundError: No module named 'elastalert')
06:33:36.096Z ERROR elastalert-server: ProcessController: ElastAlert exited with code 1

How can I fix this?

Compose file:

```
version: '3.6'

services:
  elastalert-dev:
    image: praecoapp/elastalert-server
    ports:
      - 3038:3038
      - 3339:3339
    networks:
      - net
    configs:
      - source: elastalert-dev.yaml
        target: /opt/elastalert/config.yaml
      - source: elastalert.api.config-dev.json
        target: /opt/elastalert-server/config/config.json
    deploy:
      placement:
        constraints: 
          - node.hostname == xxx
    volumes:
      - /opt/elastalert/rules:/opt/elastalert/rules
      - /opt/elastalert/rule_templates:/opt/elastalert/rule_templates
      - /opt/elastalert/server_data:/opt/elastalert/server_data

configs:
  elastalert-dev.yaml:
    external: true
  elastalert.api.config-dev.json:    
    external: true
```

## 👀 Operating environment

image: praecoapp/elastalert-server
