### ISSUE TITLE
Loosing last few alerts when realert is set to a value more than 0.

### ISSUE THREAD

**Issue by karthiknagraj** [johnsusek/praeco#423]
## 🐛 Summary
Hi, 
I am using praecoapp/elastalert-server:20211115 docker image to run elastalert server. I have been hit with an issue in which I am losing the last few alerts when **_realert_** is set to a value more than 0.  Below is the used alert rule:

```
name: alertrule-1
type: any
# event.globalRanNodeId is a unique value in the log
query_key:
   - event.globalRanNodeId
index: fluentd*
timestamp_field: "@timestamp"
realert:
  minutes: 1
filter:
- query:
    query_string:
      query: "event.eventName: \"Example Alert Occurred\""
alert:
- post:
    http_post_url: "https://webhook.site/b9b4f918-bed7-4494-8afc-810b05023e10"
    http_post_static_payload:
      fedUniqueName: "Example 1 alert"
      group: "critical alerts"
      queryKey: "event.globalRanNodeId"
alert_text: "gNB Reachability"
```

Sample log. 
```
{
    "log": "{\"event\":{\"severity\":\"Major\",\"version\":\"1.0\",\"eventName\":\"Example Alert Occurred\",\"message\":\"Example Alert Occurred\",\"currentState\":\"DOWN\",\"resourceXpath\":\"/abc\",\"previousState\":\"n/a\",\"previousMessage\":\"n/a\",\"globalRanNodeId\":\"gNBId-32\",\"gnbName\":\"example1\",\"tnlaRemoteIpAddress\":\"1.1.1.1\",\"tnlaRemotePort\":46719,\"endMarker\":\"na\"}}\n",
        "stream": "stderr",
        "docker": {
          "container_id": "182d50273a8cfb5d5635058eef47bb06219b2602bhf189940814065b23329572"
        },
        "kubernetes": {
          "container_name": "Example 1 alert",
          "namespace_name": "abc",
          "pod_name": "pod-def",
          "container_image": "praecoapp/elastalert-server:20211115",
          "pod_ip": "1.1.1.1",
          "host": "test-k8-node-3-cca082-4b2c09f7b029c4x8"
        },
        "event": {
          "severity": "Major",
          "version": "1.0",
          "eventName": "Example Alert Occurred",
          "message": "Example Alert Occurred",
          "currentState": "DOWN",
          "resourceXpath": "abc",
          "previousState": "n/a",
          "previousMessage": "n/a",
          "globalRanNodeId": "gNBId-32",
          "gnbName": "example1",
          "tnlaRemoteIpAddress": "1.1.1.1",
          "tnlaRemotePort": 46719,
          "endMarker": "na"
        },
        "@timestamp": "2021-12-23T05:25:26-0600"
}
```
Note: event.globalRanNodeId is a unique value in the log
I tried to generate 100 logs and elastalert queried elasticsearch every 1 min. When _**realert**_ is set to 0, All the 100 alerts were seen in the configured receiver, But when _**realert**_ is set to a value more than 0, alerts corresponding to the last few alerts were not triggered. Please note, I could see those logs being present in elasticsearch when elastalert queried elasticsearch. 

Error in elastalert server:
```
10:07:51.612Z ERROR elastalert-server:
    ProcessController:  WARNING:root:Querying from 2021-12-23 10:02 UTC to 2021-12-23 10:06 UTC took longer than 0:01:00!
```

## 👀 Operating environment

- Direct installation or docker: _**docker**_
- elasticsearch version: v7.10.2
- elastalert-server docker image tag name: praecoapp/elastalert-server:20211115
