### ISSUE TITLE
shorten_kibana_discover_url support

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#429]
- [ ] /src/components/config/ConfigKibanaDiscover.vue
- [ ] /src/store/config/alert.js
- [ ] /src/store/config/index.js

example

```yaml
generate_kibana_discover_url: true
shorten_kibana_discover_url: true
kibana_url: "http://kibana:5601/"
kibana_discover_app_url: "app/discover#/"
kibana_discover_index_pattern_id: "mariadblog"
kibana_discover_version: "7.16"
```
