### ISSUE TITLE
Not such file or directory on BaseRule.config when new rules are saved.

### ISSUE THREAD

**Issue by diablo02000** [johnsusek/praeco#442]
## 🐛 Describe the bug

- Docker images:
praecoapp/praeco:1.8.10
praecoapp/elastalert-server:20220109

![Capture d’écran 2022-03-04 à 11 30 40](https://user-images.githubusercontent.com/11203203/156747294-010cdfa6-71c2-43f3-91d7-9a8145e247ed.png)

![Capture d’écran 2022-03-04 à 11 31 18](https://user-images.githubusercontent.com/11203203/156747239-f05a0bb0-848c-44f4-a7d9-27364b6a422c.png)

## 👀 Steps to reproduce

1. On "rules" section create a new rules.
2. Complet the rules required fields (Name, Index, Time Type, Time Field).
3. Select MS Team destination.
4. In "Alert" section, complet Subject and Body Text field.
5. In MS Team section, add webhook url
6. Click on "save"

## Additional context

- docker-compose file:

```yaml
version: "3.9"
services:
  elastalert:
    container_name: "elastalert-server"
    image: "praecoapp/elastalert-server:20220109"
    restart: "always"
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - "/opt/elastalert-server/elastalert.yaml:/opt/elastalert/config.yaml"
      - "/opt/elastalert-server/rules.d:/opt/elastalert/rules.d"
      - "/opt/elastalert-server/config.json:/opt/elastalert-server/config/config.json"
      - "/opt/elastalert-server/rules_templates.d:/opt/elastalert/rules_templates.d"
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
  praeco:
    container_name: "praeco"
    image: "praecoapp/praeco:1.8.10"
    restart: "always"
    ports:
      - 8080:8080
    volumes:
      - "/opt/praeco/nginx-default.conf:/etc/nginx/conf.d/default.conf"
      - "/opt/praeco/nginx.conf:/etc/nginx/nginx.conf"
      - "/opt/praeco/config.json:/var/www/html/praeco.config.json"
    depends_on:
      - elastalert
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```

- ElastAlert config.json file

```json
{
  "appName": "elastalert",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules.d"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rules_templates.d"
  },
  "es_host": "172.23.220.224",
  "es_port": 9200,
  "es_ssl": true,
  "ea_verify_certs": false,
  "writeback_index": "praeco_elastalert_status"
}
```

- ElastAlert2 YAML configuration file:

```yaml
# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /opt/elastalert/rules.d

# How often ElastAlert will query Elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 15

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

old_query_limit:
  minutes: 1

# Time between each alerts
realert:
  minutes: 5

# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: "172.23.220.224"

# The Elasticsearch port
es_port: 9200

# Connect with TLS to Elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: False
# client_cert: "/opt/elastalert/elasticsearch-ca.pem"

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: "praeco_elastalert_status"

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True
```

## Comments

Look like rulesPath.path configuration are not use when we try to save the rules. It's maybe related to the hard code path in [index.js file](https://github.com/johnsusek/praeco/blob/master/src/store/config/index.js#L2441)

I don't have the error when I update the path to "rules" instead of custom path.
