### ISSUE TITLE
Add slack_webhook_url to praeco UI

### ISSUE THREAD

**Issue by andreivaloshyn** [johnsusek/praeco#518]
## 🎉 Goal

It would be great to be possible to add slack_webhook_url via Praeco UI.

## 💪 Motivation

With this feature, support specialists will be able to test alerts on their own. 

## 📖 Reference (optional)

(If there is a reference link etc.)

## 📆 Schedule (optional)

(Schedule until Closed)

## 📎 Tasks (optional)

- [x] slack_webhook_url
- [x] slack_channel_override

**Comment by nsano-rururu** [comment]
yaml

```yaml
slack_webhook_url:
  - http://xxxxx1
  - http://xxxxx2
slack_channel_override:
  - channel1
  - channel2
```
UI Image
![image](https://user-images.githubusercontent.com/22293449/228886358-e6a06bb1-f84e-40ad-8d15-81d96aaa8574.png)
