### ISSUE TITLE
How should I correctly configure the OK rule?

### ISSUE THREAD

**Issue by aratnikov-emexglobal** [johnsusek/praeco#692]
## 🐛 Summary

I have created two rules in Praeco:  
- One for a **problem alert**, which triggers when a message containing `"Attempt to create document duplicate with"` appears.  
- Another for an **OK alert**, which should trigger when no such messages appear for 10 minutes.

However, after receiving the problem alert, the OK alert did **not** trigger, even though the condition for it should have been met.

How should I correctly configure the OK rule so that it properly triggers after the problem alert?

### Problem Alert Rule
```yaml
__praeco_full_path: "myenv__my-api-attempts-to-create-document-duplicate_problem"
__praeco_query_builder: "{\"query\":{\"logicalOperator\":\"all\",\"children\":[{\"type\":\"query-builder-rule\",\"query\":{\"rule\":\"MessageTemplate\",\"selectedOperator\":\"contains\",\"selectedOperand\":\"MessageTemplate\",\"value\":\"\\\"Attempt to create document duplicate with\\\"\"}}]}}"
alert:
  - "slack"
alert_subject: "[myenv_] Attempt to create document duplicate with"
filter:
  - query:
      query_string:
        query: "MessageTemplate:\"Attempt to create document duplicate with\""
import: "BaseRule.config"
index: "prod_my-api-*"
is_enabled: true
match_enhancements: []
name: "myenv__my-api-attempts-to-create-document-duplicate_problem"
realert:
  hours: 2
slack_channel_override:
  - "#my-slack"
slack_emoji_override: ":robot_face:"
slack_msg_color: "danger"
slack_parse_override: "none"
slack_timeout: 10
slack_title_link: "http://elastalert2:8080/rules/myenv__my-api-attempts-to-create-document-duplicate_problem"
slack_username_override: "Praeco"
slack_webhook_url:
  - "https://hooks.slack.com/services/-/-"
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "any"
use_strftime_index: false
```

### **OK Alert Rule**
```yaml
__praeco_full_path: "myenv__my-api-attempts-to-create-document-duplicate_ok"
__praeco_query_builder: "{\"query\":{\"logicalOperator\":\"all\",\"children\":[{\"type\":\"query-builder-rule\",\"query\":{\"rule\":\"MessageTemplate\",\"selectedOperator\":\"contains\",\"selectedOperand\":\"MessageTemplate\",\"value\":\"\\\"Attempt to create document duplicate with\\\"\"}}]}}"
alert:
  - "slack"
alert_subject: "OK: [myenv_] Attempt to create document duplicate with"
alert_text_type: "alert_text_only"
doc_type: "properties"
filter:
  - query:
      query_string:
        query: "MessageTemplate:\"Attempt to create document duplicate with\""
import: "BaseRule.config"
index: "prod_my-api-*"
is_enabled: true
match_enhancements: []
name: "myenv__my-api-attempts-to-create-document-duplicate_ok"
realert:
  weeks: 9999
slack_channel_override:
  - "#my-slack"
slack_emoji_override: ":robot_face:"
slack_msg_color: "good"
slack_parse_override: "none"
slack_timeout: 10
slack_title_link: "http://elastalert2:8080/rules/myenv__my-api-attempts-to-create-document-duplicate_ok"
slack_username_override: "Praeco"
slack_webhook_url:
  - "https://hooks.slack.com/services/-/-"
terms_size: 50
threshold: 1
timeframe:
  minutes: 10
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "flatline"
use_strftime_index: false
```

## 👀 Operating environment

- **Installation**: Docker  
- **Elasticsearch version**: `7.17.18`  
- **Praeco version**: `praecoapp/praeco:1.8.20`  
- **Elastalert-server docker image tag**: `praecoapp/elastalert-server:20241227`  

## 📎 Images (optional)

![Image](https://github.com/user-attachments/assets/5c763021-beac-4a24-92b6-418240fe78f8)

Thanks in advance!
